name: DevSecOps Standard Workflow

on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
      region:
        required: true
        type: string
      function_name:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string

jobs:
  security-scan:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # MarketplaceのTrivyを利用して、コード内の脆弱性や誤ってPushされたシークレットをスキャン
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH' # 重大な脆弱性のみ検出してブロック

  deploy:
    name: Auth and Deploy
    needs: security-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: Deploy to Cloud Functions
        uses: google-github-actions/deploy-cloudfunctions@v2
        with:
          name: ${{ inputs.function_name }}
          runtime: python311
          region: ${{ inputs.region }}
          project_id: ${{ inputs.project_id }}
          entry_point: hello_world
          gen2: true
